name: Falcon
 
on:
  #schedule:
    # * is a special character in YAML so you have to quote this string
  #  - cron:  '0 19 * * *'
  workflow_dispatch:
  pull_request:
    branches: [v0.8]
 
jobs:
  falcon:
    name: Scan
    runs-on: ubuntu-latest
    # Skip any PR created by dependabot to avoid permissioning issues
    if: (github.actor != 'dependabot[bot]')
    steps:
      # Checkout project source
      - uses: actions/checkout@v2
      - name: Create zip archive
        run: zip -r upload.zip *
      # Upload & scan
      - uses: actions/checkout@v2
        with:
          repository: logrhythm/ociso-falcon-upload-and-scan-action
          ref: v0.1.6
          token: ${{secrets.GH_TOKEN}}
          path: .github/ociso-falcon-upload-and-scan-action
      - name: Upload and scan
        uses: ./.github/ociso-falcon-upload-and-scan-action
        with:
          accesskey: ${{secrets.ACCESS_KEY}}
          secretkey: ${{secrets.SECRET_KEY}}
          language: 'javascript'
          product: 'SE'
          project: 'ez-cloud'
          comment: ${{ github.run_id }}
          email: 'tony.masse@logrhythm.com'
          file: 'upload.zip'
